### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by geekdave** [virtual-kubelet/aws-fargate#5]
Thanks to all the contributors for your work on this project!  Auto scaling pods without worrying about the underlying nodes is exciting!  I noticed there was a lot of activity in this repo that seemed to stop suddenly in June 2019.  Is this project still going to continue?

![Contributors_to_virtual-kubelet_aws-fargate](https://user-images.githubusercontent.com/1438478/69201590-9fa5df00-0af3-11ea-8667-725c2b6ab1c4.jpg)

**Comment by cpuguy83** [comment]
The activity you see is from before this was split off from virtual-kubelet/virtual-kubelet.

**Comment by geekdave** [comment]
@cpuguy83 Thanks for clarifying.  Going forward will this repo be maintained?

**Comment by cpuguy83** [comment]
I don't plan to, it's largely up to the community.

**Comment by pires** [comment]
I think we just learned from AWS re:Invent that AWS went their own way w/ EKS on Fargate, meaning closed source. There was no mention to VK so it's unclear how much _inspiration_ they took from this work but looking at the contributor list and the AWS folks being vocal on social media about their new product, my hunch is a lot.

**Comment by cpuguy83** [comment]
I've added a project status to the readme, marking it as inactive and seeking maintainers.
